name: Build Executables

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install pyinstaller
      
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --windowed --name Roblox2Rojo-Windows --add-data "src;src" main.py
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Roblox2Rojo-Windows
          path: dist/Roblox2Rojo-Windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          pip install pyinstaller
      
      - name: Build Linux executable
        run: |
          pyinstaller --onefile --windowed --name Roblox2Rojo-Linux --add-data "src:src" main.py
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Roblox2Rojo-Linux
          path: dist/Roblox2Rojo-Linux

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install pyinstaller
      
      - name: Build macOS executable
        run: |
          pyinstaller --onefile --windowed --name Roblox2Rojo-macOS --add-data "src:src" main.py
      
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Roblox2Rojo-macOS
          path: dist/Roblox2Rojo-macOS

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Generate changelog
        id: changelog
        run: |
          echo "## What's Changed" > CHANGELOG.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Downloads" >> CHANGELOG.md
          echo "Choose the version for your operating system below." >> CHANGELOG.md
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            Roblox2Rojo-Windows/Roblox2Rojo-Windows.exe
            Roblox2Rojo-Linux/Roblox2Rojo-Linux
            Roblox2Rojo-macOS/Roblox2Rojo-macOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
